#{ 5 
S ::= DEFINITIONS

DEFINITIONS ::= DEFINITION DEFINITIONS_TAIL
DEFINITIONS_TAIL ::= DEFINITION DEFINITIONS_TAIL
        | ε

DEFINITION ::= SIGNATURE ";"
        | DEF ";"
        | DATA_TYPE_DECL ";"

SIGNATURE ::= id "::" TYPE_SIGNATURE
#} 5


#{ 6
TYPE_SIGNATURE ::= TYPE TYPE_SIGNATURE_TAIL
TYPE_SIGNATURE_TAIL ::= "->" TYPE TYPE_SIGNATURE_TAIL
        | ε

TYPE ::= SIMPLE_TYPE
        | "(" TYPE_SIGNATURE ")"

SIMPLE_TYPE ::= id
        | LIST_TYPE
        | "(" type_constructor TYPE_ARGUMENTS ")"

LIST_TYPE ::= "[" TYPE "]"

TYPE_ARGUMENTS ::= TYPE TYPE_ARGUMENTS
        | ε
#} 6


#{ 7
DEF ::= FUNCTION_DECL
        |  VARIABLE_DECL

FUNCTION_DECL ::= id PATTERNS "=" EXPR
VARIABLE_DECL ::= id "=" EXPR
#} 7


#{ 8
DATA_TYPE_DECL ::= "data" CONSTRUCTOR "=" CONSTRUCTORS

CONSTRUCTORS ::= CONSTRUCTOR CONSTRUCTORS_TAIL
CONSTRUCTORS_TAIL ::= "|" CONSTRUCTOR CONSTRUCTORS_TAIL
        | ε

CONSTRUCTOR ::= type_constructor TYPE_ARGUMENTS
#} 8


#{ 4
PATTERNS ::= PATTERN PATTERNS_TAIL
PATTERNS_TAIL ::= PATTERN PATTERNS_TAIL
        | ε

PATTERN ::= id
        | LITERAL
        | "_"
        | "(" CONSTRUCTOR_PATTERN ")"
        | LIST_PATTERN
        | TUPLE_PATTERN

CONSTRUCTOR_PATTERN ::= type_constructor PATTERNS
        | type_constructor

TUPLE_PATTERN ::= "(" LIST_PATTERNS ")"

LIST_PATTERN ::= "[" LIST_PATTERNS "]"
        | "(" id ":" id ")"
LIST_PATTERNS ::= PATTERN LIST_PATTERNS_TAIL
        | ε
LIST_PATTERNS_TAIL ::= "," PATTERN LIST_PATTERNS_TAIL
        | ε
#} 4


#{ 3
LIST_COMPREHENSION ::= "[" EXPR "|" QUALIFIERS "]"
QUALIFIERS ::= QUALIFIER QUALIFIERS_TAIL
        | ε
QUALIFIERS_TAIL ::= "," QUALIFIER QUALIFIERS_TAIL
        | ε
QUALIFIER ::= id "<-" EXPR
        | "let" BIND
        | EXPR
#} 3


#{ 2
IF_EXPR ::= "if" EXPR "then" EXPR "else" EXPR
LET_EXPR ::= "let" "{" BINDINGS "}" "in" EXPR
WHERE_EXPR ::= EXPR "where" "{" BINDINGS "}"
LAMBDA_EXPR ::= "\\" PATTERN "->" EXPR

CASE_EXPR ::= "case" EXPR "of" "{" ALTS "}"
ALTS ::= PATTERN "->" EXPR ";" ALTS_TAIL
ALTS_TAIL ::= PATTERN "->" EXPR ";" ALTS_TAIL
        | ε

BINDINGS ::= BIND ";" BINDINGS_TAIL
BINDINGS_TAIL ::= BIND ";" BINDINGS_TAIL
        | ε
BIND ::= id "=" EXPR 
        | id PATTERNS "=" EXPR 
        | SIGNATURE
#} 2


#{ 9
OR_EXPR ::= OR_EXPR "||" AND_EXPR
        | AND_EXPR

AND_EXPR ::= AND_EXPR "&&" COMP_EXPR
        | COMP_EXPR

COMP_EXPR ::= COMP_EXPR "==" CONS_EXPR 
        | COMP_EXPR "/=" CONS_EXPR
        | COMP_EXPR "<" CONS_EXPR
        | COMP_EXPR ">" CONS_EXPR
        | COMP_EXPR "<=" CONS_EXPR
        | COMP_EXPR ">=" CONS_EXPR
        | CONS_EXPR

CONS_EXPR ::= ADDITIVE_EXPR ":" CONS_EXPR
        | ADDITIVE_EXPR "++" CONS_EXPR
        | ADDITIVE_EXPR

ADDITIVE_EXPR ::= ADDITIVE_EXPR "+" MULTIPLICATIVE_EXPR
        | ADDITIVE_EXPR "-" MULTIPLICATIVE_EXPR
        | MULTIPLICATIVE_EXPR

MULTIPLICATIVE_EXPR ::= MULTIPLICATIVE_EXPR "*" UNARY_MINUS
        | MULTIPLICATIVE_EXPR "/" UNARY_MINUS
        | UNARY_MINUS

UNARY_MINUS ::= "-" TERM
        | TERM

TERM ::= LITERAL
        | id
        | "(" EXPR ")"
        | "[" LIST_ELEMENTS "]"
        | "(" TUPLE_ELEMENTS ")"
        | "(" FUNCTION_CALL ")"
        | type_constructor ARG_LIST

TUPLE_ELEMENTS ::= EXPR "," EXPR TUPLE_ELEMENTS_TAIL
TUPLE_ELEMENTS_TAIL ::= "," EXPR TUPLE_ELEMENTS_TAIL
        | ε

LIST_ELEMENTS ::= EXPR LIST_ELEMENTS_TAIL
        | ε
LIST_ELEMENTS_TAIL ::= "," EXPR LIST_ELEMENTS_TAIL
        | ε

FUNCTION_CALL ::= ARG_EXPR ARG_EXPR ARG_LIST
ARG_LIST ::= ARG_EXPR ARG_LIST
        | ε
ARG_EXPR ::= "(" EXPR ")"
        | id
        | LITERAL
        | "(" FUNCTION_CALL ")"
        | "[" LIST_ELEMENTS "]"
        | "(" TUPLE_ELEMENTS ")"
#} 9


#{ 1
EXPR ::= OR_EXPR
        | IF_EXPR
        | LET_EXPR
        | LIST_COMPREHENSION
        | LAMBDA_EXPR
        | WHERE_EXPR
        | CASE_EXPR

LITERAL ::= literal_int
        | literal_float
        | literal_string
        | literal_char

id ::= [a-z][a-zA-Z0-9]* 
type_constructor ::= [A-Z][a-zA-Z0-9]*
literal_int ::= [0-9]+
literal_float ::= [0-9]+"."[0-9]+
literal_string ::= \"[^"]*\" 
literal_char ::= \'[^']\' 

#} 1